### 启动设备
get http://192.168.10.115:8999/tongue_public/equipment/start?id=11223344&openId=fake_openid


### 状态
get http://192.168.10.115:8999/tongue_public/equipment/result?id=11223344&openId=fake_openid


### 公众号 co-wechat 
get http://localhost:3001/wx/wechat?signature=b3df839c53d6884f86ba123e0e0a0665731a290a&echostr=8526463064474320774&timestamp=1684205444&nonce=806093144


### 测试号 access_token 获取
@appid=wxea4c1a271d231129
@secret=bff305946858377c27317fa6bc02d99d
get https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={{appid}}&secret={{secret}}


### 测试号 菜单设置
@token=68_N8_oH1aCaPRlbdQtUGvAbvEf6Y6u-DvFAKmzZvSB7LOAMeVEYt4XBm7vPv3d4qJySc8SIOlZMc3ipngYg_z86J5nCYPvIX1LIbugWhC5kpo4J9FS46Jpkgl_100QYLhAIABJW

POST https://api.weixin.qq.com/cgi-bin/menu/create?access_token={{token}}
Content-Type: application/json

{
  "button":[
    {	
      "type":"view",
      "name":"我要体验",
      "key": "start",
      "url": "https://www.fengyenongye.cn/wangzhi_wx/index.html"
    }
  ]
}

### 真实号
@appid1=wxe612c154760180a2
@secret1=c963df09303ec637552c443779acfcb1
get https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={{appid1}}&secret={{secret1}}


### 真实号修改菜单
@token1=68_m4v83S2iTILLLrV3pbL7yclz7rO9Ql8HieBAOf0g7MuNOnkarkcBt0CWIBgp3rLm5FE-mE0xLpBJk3xfirfsm1DFi4Ov55Cn9mwqIZAKja9yTLJaEqc8bJDXfNEPAHeACADOV
POST https://api.weixin.qq.com/cgi-bin/menu/create?access_token={{token1}}
Content-Type: application/json

{
  "button":[
    {	
      "type":"view",
      "name":"我要体验",
      "key": "start",
      "url": "https://www.fengyenongye.cn/wangzhi_wx/index.html"
    }
  ]
}